version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: todo_app_list
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: release_image
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
